### ISSUE TITLE
Latest Release doesn't seem to work with latest Babel

### ISSUE THREAD

**Issue by InfiTanj** [H256/gekko-quasar-ui#11]
First thanks,  I really appreciate all your work and am a fan of the previous release.
However, Version 0.6.6.20180916 is giving me trouble with babel.  It looks like you are using an older version than the current release.  I suspect my issue could be fixed by just knowing how to install babel to match your build environment.

Anyway here is what I did:
git clone https://github.com/H256/gekko-quasar-ui.git
cd gekko-quasar-ui
npm install
npm install autoprefixer
npm install @babel/core --save-dev
npm install @babel/plugin-transform-runtime --save-dev
npm install @babel/preset-env --save-dev
npm install @babel/preset-stage-2 --save-dev
npm install babel-plugin-transform-imports --save-dev

And here is what happened:
quasar dev
-----------------------
 ERROR  Failed to compile with 1 errors                                                                                                                                                  4:33:35 PM

 error  in ./.quasar/client-entry.js

Module build failed (from /usr/lib/node_modules/quasar-cli/node_modules/babel-loader/lib/index.js):
  Error: [BABEL] /home/tanj/gekko-quasar-ui/.quasar/client-entry.js: The 'polyfill' option has been removed. The @babel/runtime module now skips polyfilling by default. (While processing: "/home/  tanj/gekko-quasar-ui/node_modules/@babel/plugin-transform-runtime/lib/index.js")
  
  - index.js:131 _default
    [gekko-quasar-ui]/[@babel]/plugin-transform-runtime/lib/index.js:131:13
  
  - index.js:19 
    [gekko-quasar-ui]/[@babel]/helper-plugin-utils/lib/index.js:19:12
  
  - full.js:157 loadDescriptor
    [lib]/[quasar-cli]/[@babel]/core/lib/config/full.js:157:14
  
  - caching.js:32 cachedFunction
    [lib]/[quasar-cli]/[@babel]/core/lib/config/caching.js:32:19
  
  - full.js:192 loadPluginDescriptor
    [lib]/[quasar-cli]/[@babel]/core/lib/config/full.js:192:28
  
  - full.js:68 config.plugins.map.descriptor
    [lib]/[quasar-cli]/[@babel]/core/lib/config/full.js:68:16
  
  - Array.map
  
  - full.js:67 recurseDescriptors
    [lib]/[quasar-cli]/[@babel]/core/lib/config/full.js:67:38
  
  - full.js:100 loadFullConfig
    [lib]/[quasar-cli]/[@babel]/core/lib/config/full.js:100:6
  
  - transform.js:28 process.nextTick
    [lib]/[quasar-cli]/[@babel]/core/lib/transform.js:28:33
  

 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

_____________________________________

Thanks in advance for any assistance in getting this running.

**Comment by H256** [comment]
I've tried to reproduce on a fresh Linux Mint 19 VM.
On Node 8.12.0 LTS, I also had some problems... coming from quasar-cli not being installed correctly (this installs all needed babel-dependencies as well).

To fix, I did the following:
1. Make sure, Node and NPM are properly installed.
2. Install the latest quasar-framework as described here: https://quasar-framework.org/guide/index.html#Development-with-Quasar-CLI-Recommended
3. Follow my Readme on this repo.

If it doesn't install my dependencies correctly, manually install them into gekko-quasar-ui with 
`npm install --save axios humanize-duration moment vue-echarts vue-i18n vue-json-excel`

I will extend the Readme accordingly ;)

**Comment by InfiTanj** [comment]
Thanks.

I must have something messed up in my environment.
npm install -g quasar-cli
npm install -g vue-cli
did nothing... but I had to sudo to install them global.
I am also using node 10.10 instead of Node 8.12.0 LTS, not sure if that matters.

However, simply installing them in gekko-quasar-ui  local (without the -g) however worked fine.
npm install quasar-cli
npm install vue-cli
npm install
npm install --save axios humanize-duration moment vue-echarts vue-i18n vue-json-excel

and it compiles and runs fine with 
quasar dev

Thanks.  I really do appreciate all your work, and that you share it!

**Comment by H256** [comment]
@InfiTanj I'm glad it works now! :) I hope the UI will be of use for you ;)

**Comment by matthhong** [comment]
Here's what I did for `quasar build` to work on my Mac (npm 5.6.0, node 8.11.2), immediately after newly cloning this repository:

1. Delete the `"polyfill": false,` from line 16 of the .babelrc file.

- This gets rid of the original error @InfiTanj reported.

2. Run `npx babel-upgrade --write`.

- This upgrades the .babelrc file so that it doesn't depend on [Stage presets](https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets).

3. Change the `"requires": true,` from line 5 of `package-lock.json` to `"requires": false,`

- If you don't do this, none of the dependencies in `package.json` will install. *If you missed this step before running `npm install`, clone the entire repository again.*

4. `npm install` and `quasar build`.

**Comment by H256** [comment]
@matt1hong Thanks for pointing this out. I've done these steps and uploaded the updated babelrc file.
