### ISSUE TITLE
missing time set in csv/xls when downloading Backest from Backtest

### ISSUE THREAD

**Issue by verbraucher** [H256/gekko-quasar-ui#14]
**Action taken** (what you did)
I download a csv/xls from any Backtest.

**Expected result**
I miss a time set in the backtest-result (csv/xls)

**Actual result** (unexpected outcome)
In the backtest-result (csv/xls) is no entry for any given time.

![image](https://user-images.githubusercontent.com/22300791/47430737-7d2f7e00-d79a-11e8-9dec-797325be2e3a.png)

**Comment by H256** [comment]
I've aded a Patch to reformat values from unix-timestamps to human readable format. The timestamp is located in the column "start".
