### ISSUE TITLE
How can tulip-indicators be displayed in the market graph?

### ISSUE THREAD

**Issue by verbraucher** [H256/gekko-quasar-ui#15]
**Action taken** (what you did)
I write my own strategy with some tulip-indicators.
```
strat.init = function() {
  this.addTulipIndicator('ema10','ema',{
	  optInTimePeriod: 10
  });
  this.addTulipIndicator('ema21','ema',{
	  optInTimePeriod: 21
  });
}
```

**Expected result** (what you hoped would happen)
I want the indicators to be displayed in the market graph.

**Actual result** (unexpected outcome)
there is no overlay in the market graph

How can the indicators be displayed in the market graph?

**Comment by H256** [comment]
Normally it should choose to display indicators as overlay. 
What Gekko-Version are you using? Maybe it doesn't send the values to the client.

**Comment by verbraucher** [comment]
I use gekko v0.6.6.
Thanks for your help!

**Comment by H256** [comment]
Ok, 0.6.6 should send you a property `stratUpdates` inside the backtest-result. If this is not the case there might be something wrong with Quasar or Vue idk (the feature is enabled from within the frontend).
You should be able to force Gekko to send these results by editing `<gekko-path>/web/routes/baseConfig.js` and setting `stratUpdates: true`  around line 27 in the file. After that restart gekko.

**Comment by verbraucher** [comment]
> Ok, 0.6.6 should send you a property `stratUpdates` inside the backtest-result. If this is not the case there might be something wrong with Quasar or Vue idk (the feature is enabled from within the frontend).
> You should be able to force Gekko to send these results by editing `<gekko-path>/web/routes/baseConfig.js` and setting `stratUpdates: true` around line 27 in the file. After that restart gekko.

That did not work either :/

**Comment by verbraucher** [comment]
With the new version of gekko v0.6.7 the tulip indicators will be displayed!
See in the changelog (https://github.com/askmike/gekko/pull/2612):

> ...
> [CORE] Add Tulip and Talib Indicator-Results to 'stratUpdate' event (#2483 - @H256)
> ...
