### ISSUE TITLE
How is it possible to display the extendended Market graph?

### ISSUE THREAD

**Issue by verbraucher** [H256/gekko-quasar-ui#17]
On the last picture of the description page is displayed an extended Market graph where you can select indicators and choose the direction of the axis. 
How we can use this extended view (there is written: "applies only to patched version")?

![image](https://user-images.githubusercontent.com/22300791/47501958-fa282980-d866-11e8-9264-b3e2fd5feeab.png)

**Comment by H256** [comment]
Hi @verbraucher, nice find. This screenshot is outdated. The feature is not available anymore and has been replaced by a more "generic" approach, where the UI tries to to place indicator results in two different sections of the chart. All indicators that are possible to overlay the market-graph will be rendered directly into the candle-chart als lines. All other indicators are placed in the lower section of the chart.
