### ISSUE TITLE
Dist/spa empty

### ISSUE THREAD

**Issue by ethcar** [H256/gekko-quasar-ui#18]
Unable to find the files to copy for UI

**Comment by H256** [comment]
Hi. Please supply more information. Did you follow the steps from readme? Did any error messages appear?

**Comment by ethcar** [comment]
Thank you for your reply,

I managed to get the issue resolved. However when running the quasar Dev or quasar build, after following all the steps get an api errors.

New live gekko does not get started, unable to run backtests.

http://prntscr.com/mk8obc

When starting a live gekko get the following errors
http://prntscr.com/mk8pp5

**Comment by H256** [comment]
Looks like the pair does not exist on the selected exchange - what exchange and pair are you using?
That might happen since gekkos's pair-infos are not always up to date.

**Comment by ethcar** [comment]
I know the issue has been there on poloniex pairs, I have tried all exchanges and different pairs, This issue should not occur if running in dev mode as it is fetching the data from the running instance of gekko UI.
I have tried new installations, cross installation, even followed the steps to build the new UI and got all the files and made changes as instructed. Do you have it running fine on your end ?

**Comment by H256** [comment]
Yes, I got it running on my end. But I could reproduce you problem with for example 
Poloniex - BTC-1CR or 
Poloniex BTC-AUR - these are not available for trading anymore.

The error also occurs in the original UI. 
It seems to be the market files that have to be updated.
Most of the files (except for poloniex) can be updated manually - this is described here:
https://github.com/askmike/gekko/issues/2605

The problem seems not to be related to this repository, may I ask you to open an issue directly in the original repo for the gekko-bot (to update poloniex)?

**Comment by ethcar** [comment]
Hi,

Is it possible if you can upload your complete gekko, with your UI running in your personal repository.
If you do so please make sure to remove the API keys from your source code. 
I am not a developer, but am fine with following instructions. If you upload your files in your repository it will fix my issue which I am trying to resolve from past few days.

Thanks in advance.

**Comment by H256** [comment]
Here you go - clone this repo:
https://github.com/H256/gekko
After that, run `npm install` on the root path (e.g. c:\gekko\) and on the exchanges path (e.g. c:\gekko\exchange).
Then run `node gekko --ui`. This should start the server including new UI on localhost.

**Comment by ethcar** [comment]
Great, Thank you for your help and effort.
It is working now. 
Have a great day

**Comment by ethcar** [comment]
Hi, 
I just sent 0.01 BTC, as a thank you for your help, as earlier I was unable to find your BTC address on the profile. https://www.blockchain.com/btc/tx/52279416fcc149f2463bbaec0ac79bfcfc33f796fe94e219d51f92aefb05d3de

However I do have an ongoing issue, I was never able to run the gekko on server(even normal gui),
The only way I was able to accomplish it was through docker, I wish to run your GUI on server, but when I run docker image only normal GUI works, If I use your repo, It does not.

I have your GUI working on my desktop, and have one instance Gekko running on server, via Docker
Thank you

**Comment by H256** [comment]
Hi @ethcar, first of all thanks for you donation. Since the problem is referenced to the "complete repository" - I have opened and referenced an issue there.
