### ISSUE TITLE
[Bug] Indicators are not render on right timestamp

### ISSUE THREAD

**Issue by PSheon** [H256/gekko-quasar-ui#20]
I'm submitting a ...
[ x] bug report

Action taken (what you did)
Trade indicators render correctly on backtest but live-trade or papertrade are not

Expected result (what you hoped would happen)
![image](https://user-images.githubusercontent.com/20603727/58241922-709af480-7d80-11e9-990a-3bdcca94bdbf.png)

Actual result (unexpected outcome)
![image](https://user-images.githubusercontent.com/20603727/58242032-b1930900-7d80-11e9-82c3-25fdd0b86fa8.png)

**Comment by H256** [comment]
fixed by pr
