### ISSUE TITLE
[Bug] _ indicators are static

### ISSUE THREAD

**Issue by segatrade** [H256/gekko-quasar-ui#22]
Indicators with _ in name are static on chart (visible like horizontal line). For example standard PPO vs standard MACD indicator. PPO is error = static line of one number on chart. MACD is OK - different values.

I updated to https://github.com/H256/gekko with last commit on 2/21/19 . Used before it old version with gekko 0.5.x and worked OK

**Comment by H256** [comment]
Hi, @segatrade thanks for your report. 
There seems something wrong with emitted strategy-updates in the original gekko repo. I have deployed a fix to my fork that was working on my side. Could you please test by pulling the current development branch again from here: https://github.com/H256/gekko - just give me short feedback if this is resolved by the patch.

(I also updated this version to be based on the current changes inside the original repo)...

**Comment by segatrade** [comment]
Hi, @H256 thanks you very much for your project and fast reply.
Fix seems is working.
Thank you.
