### ISSUE TITLE
Missing file .babelrc

### ISSUE THREAD

**Issue by wuxiacn0707** [H256/gekko-quasar-ui#27]
can you upload it.

**Comment by H256** [comment]
There's no need for that file. Quasar uses `babel.config.js` from the root folder AFAIK.

**Comment by wuxiacn0707** [comment]
![微信图片_20191106154258](https://user-images.githubusercontent.com/48899678/68278558-89882f80-00ac-11ea-90b1-550dd97b8887.png)

**Comment by wuxiacn0707** [comment]
ok. fix it. 
Thank you!

**Comment by wuxiacn0707** [comment]
fix it. Thank you!
