### ISSUE TITLE
Remark - gekko-quasar-ui install on linux (Ubuntu 20.04)

### ISSUE THREAD

**Issue by SvenMey** [H256/gekko-quasar-ui#31]
Hello H256

I just got your project to work on Ubuntu and I like it very much.

For me the 'npm install' does not work and I ended up in dependency hell.

Hence, I installed yarn and 'yarn install' worked directly out-of-the-box.
May I suggest to mention this in your README.

Thank you for that and keep up the good work.

KR

**Comment by H256** [comment]
Thanks. Mentioned it in the readme.
