### ISSUE TITLE
Using Quasar UI like a main UI for gekko

### ISSUE THREAD

**Issue by elmankross** [H256/gekko-quasar-ui#8]
Thanks for your big work!
Please correct documentation part for "[Compile for replacing the original Gekko-UI](https://github.com/H256/gekko-quasar-ui#compile-for-replacing-the-original-gekko-ui)"
it should be one more step after (6):
Edit ~`line 87` in `web -> server.js`:
replace 
```
app
  .use(cors())
  .use(serve(WEBROOT + 'vue/dist'))
  .use(bodyParser())
  .use(require('koa-logger')())
  .use(router.routes())
  .use(router.allowedMethods());
```
with 
```
app
  .use(cors())
  .use(serve(WEBROOT + 'vue'))
  .use(bodyParser())
  .use(require('koa-logger')())
  .use(router.routes())
  .use(router.allowedMethods());
```
Gekko v. 0.6.5

**Comment by H256** [comment]
Thanks for the hint. Actually the UI should'nt be working at all with Gekko > 0.6.5 because of massively changed events and API. I will get to this as soon as I have some time to update everything to the new 0.6+ events-api.

**Comment by H256** [comment]
Udated to work with 0.6 Gekkos.

**Comment by elmankross** [comment]
> Udated to work with 0.6 Gekkos.

@H256 I don't know it's a bug or feature but there is no live tradings on dashboard - https://ibb.co/mgacaK
_Gekko v0.6.6_
_Gekko-quasar-ui v0.5.24_

**Comment by H256** [comment]
@elmankross please try to pull the latest version - I've made some changes in the meantime.

**Comment by elmankross** [comment]
@H256 it works 👍
