### ISSUE TITLE
UI desktop

### ISSUE THREAD

**Issue by npolevara** [H256/gekko-quasar-ui#9]
Hi! This really good work, i have some visual improvement for your ui.
1. H3 fonts to big, on my mac 13'' i use 25px for H3.
2. Top panel  with slider, and footer steal monitor heigth, i hide it by display:none css option.
If the sidebar with links to the community is needed - you can place the button in the panel with gekko tabs in the first place.
3. I make some fonts and icons smaller, now more information is available on the screen, the same applies to the transaction table.
[http://joxi.ru/MAj1QW7H4nwYw2](screen)

**Comment by H256** [comment]
I have changed some thing to improve visibility. I will make more changes next time when I'm working on the individual components.
